CREATE EXTENSION IF NOT EXISTS vector;

CREATE SCHEMA IF NOT EXISTS order_svc AUTHORIZATION commerce;
CREATE SCHEMA IF NOT EXISTS payment_svc AUTHORIZATION commerce;
CREATE SCHEMA IF NOT EXISTS inventory_svc AUTHORIZATION commerce;
CREATE SCHEMA IF NOT EXISTS ai_svc AUTHORIZATION commerce;
