spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/commerce?currentSchema=payment_svc
    username: commerce
    password: commerce
    hikari:
      schema: payment_svc
  jpa:
    properties:
      hibernate:
        default_schema: payment_svc
        jdbc.time_zone: UTC
    open-in-view: false
  flyway:
    schemas: [payment_svc]
    default-schema: payment_svc
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:29092
    properties:
      schema.registry.url: http://localhost:8085
    consumer:
      group-id: payment-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufSerializer
      acks: all
      enable-idempotence: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8088/realms/commerce

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
